project_id = "mlifhlmnxgwaufmbttup"

[functions.chat]
verify_jwt = false

[functions.send-approval-email]
verify_jwt = true

[functions.send-tutorial-approval-email]
verify_jwt = true

[functions.notify-telegram-purchase]
verify_jwt = false